### ISSUE TITLE
그룹에 가입되지 않은 아이디로 로그인 한 후 그룹 탭에 들어가면 강제 종료돼요!

### ISSUE THREAD

**Issue by SongKong00** [Relay-UMC23/relay-android#40]
![image](https://user-images.githubusercontent.com/114280643/218378149-1b989faf-9433-4774-883a-e44ac4fce433.png)

그룹에 가입하지 않은 아이디인 경우 clubIdx가 null 값이어서 앱이 강제 종료되는 것 같습니다!
처리가 필요할 것 같아요..!

**Comment by limsubinn** [comment]
response 코드가 바꼈더라구요! 로컬에는 수정되어 있는 상태이고 머지 되면 해결될 거예요!
